command:
  - "sh"
  - "-c"
  - "npm install && cd client && npm install && npm run build && cd .. && npm start"

env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "8080"
  - name: PGHOST
    value: your-postgres-host.example.com
  - name: PGPORT
    value: "5432"
  - name: PGDATABASE
    value: scorex_postgres
  - name: PGUSER
    value: support@example.com
  - name: PGPASSWORD
    value: "{{secrets/scorex/PGPASSWORD}}"
  - name: SESSION_SECRET
    value: "{{secrets/scorex/SESSION_SECRET}}"
