import axios from 'axios';
import authService from './authService';

const API_BASE_URL = process.env.REACT_APP_API_URL ||
  (window.location.hostname === 'localhost' ? 'http://localhost:5001/api' : '/api');

function extractFilename(contentDisposition, fallbackName) {
  if (!contentDisposition) return fallbackName;

  const utf8Match = contentDisposition.match(/filename\*=UTF-8''([^;]+)/i);
  if (utf8Match?.[1]) {
    try {
      return decodeURIComponent(utf8Match[1].replace(/["']/g, ''));
    } catch (_) {
      // Fall through to standard filename handling.
    }
  }

  const filenameMatch = contentDisposition.match(/filename="?([^";]+)"?/i);
  return filenameMatch?.[1] || fallbackName;
}

/**
 * Export assessment data to an Excel workbook generated by the secured server endpoint.
 *
 * This intentionally avoids generating XLSX files in the browser. The previous browser-side
 * `xlsx` dependency had unresolved high-severity advisories; ScoreX already has an ExcelJS
 * server exporter protected by assessment ownership checks, so all exports now use that path.
 */
export const exportAssessmentToExcel = async (assessmentId, assessmentName = 'Assessment') => {
  if (!assessmentId) throw new Error('Assessment ID is required');

  let sessionId = localStorage.getItem('sessionId');
  if (!sessionId) {
    authService.createGuestSession();
    sessionId = localStorage.getItem('sessionId');
  }

  try {
    const response = await axios.get(`${API_BASE_URL}/assessment-excel/${encodeURIComponent(assessmentId)}/export`, {
      responseType: 'blob',
      timeout: 120000,
      headers: sessionId ? { 'x-session-id': sessionId } : undefined
    });

    const safeName = String(assessmentName || 'Assessment').replace(/[^a-z0-9_-]+/gi, '_');
    const fallbackName = `${safeName}_${new Date().toISOString().split('T')[0]}.xlsx`;
    const fileName = extractFilename(response.headers?.['content-disposition'], fallbackName);

    const blob = response.data instanceof Blob
      ? response.data
      : new Blob([response.data], {
          type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        });

    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = fileName;
    anchor.style.display = 'none';
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);

    return { success: true, fileName };
  } catch (error) {
    console.error('[Excel Export] Server export failed:', error.response?.status || error.message);
    throw new Error(error.response?.data?.error || error.message || 'Failed to export Excel workbook');
  }
};
